apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true

    processors:
      - add_cloud_metadata: ~

    output.elasticsearch:
      hosts: ["52.66.243.171:9200"]
      username: "admin"
      password: "sheero"

    setup.kibana:
      host: "52.66.243.171:5601"
